name: Deploy to ECS
description: Build Docker image, push to ECR, and deploy to ECS

inputs:
  aws-iam:
    description: AWS account ID to assume role in
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-iam }}:role/gha-access
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5

    - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Build and tag the Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: bors
        IMAGE_TAG: latest
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      with:
        context: .
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: GIT_VERSION=${{ github.sha }}

    - name: Kick ECS to deploy new version
      shell: bash
      run: |
        aws ecs update-service --service bors --cluster bors --force-new-deployment
        # Poll every 15 seconds until a successful state has been reached. Fail after 40 failed checks.
        aws ecs wait services-stable --services bors --cluster bors
