name: Deploy to ECS
description: Build Docker image, push to ECR, and deploy to ECS

inputs:
  aws-iam:
    description: AWS account ID to assume role in
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-iam }}:role/gha-access
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # v2.1.2

    - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Build and tag the Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: bors
        IMAGE_TAG: latest
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: .
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: GIT_VERSION=${{ github.sha }}

    - name: Kick ECS to deploy new version
      shell: bash
      run: |
        aws ecs update-service --service bors --cluster bors --force-new-deployment
        # Poll every 15 seconds until a successful state has been reached. Fail after 40 failed checks.
        aws ecs wait services-stable --services bors --cluster bors
