name: Deploy staging

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging
    if: github.repository_owner == 'rust-lang'
    permissions:
      id-token: write # required for OIDC authentication to AWS
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Deploy to ECS
        uses: ./.github/actions/deploy-ecs
        with:
          aws-iam: "392478027976"
