name: Deploy production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    if: github.repository_owner == 'rust-lang'
    permissions:
      id-token: write # required for OIDC authentication to AWS
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Deploy to ECS
        uses: ./.github/actions/deploy-ecs
        with:
          aws-iam: "351621253146"
