name: Deploy production

permissions: {}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    if: github.repository_owner == 'rust-lang'
    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
        with:
          persist-credentials: false
      - name: Deploy to ECS
        uses: ./.github/actions/deploy-ecs
        with:
          aws-iam: "351621253146"
